/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_averycowan_screenprotector_LockMechanism */

#ifndef _Included_com_averycowan_screenprotector_LockMechanism
#define _Included_com_averycowan_screenprotector_LockMechanism
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_averycowan_screenprotector_LockMechanism
 * Method:    nativeLock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_averycowan_screenprotector_LockMechanism_nativeLock
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
